version: 3.1.0
services:
  mongo-db:
    image: mongo:7.0.4
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
      MONGO_INITDB_DATABASE: rajds
      MONGO_INITDB_USERNAME: rajds
      MONGO_INITDB_PASSWORD: rajds
    volumes:
      - ./scripts/mongo:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine3.18
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass P@ssw0rd