name: Manual Build

on: workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ "linux", "darwin" ]
        arch: [ "arm64", "amd64" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.6
      - name: Build-CP
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o rajds-cp-${{ matrix.os }}-${{ matrix.arch }} ./cmd/controlplane/main.go
      - name: Build-Worker
        run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o rajds-worker-${{ matrix.os }}-${{ matrix.arch }} ./cmd/worker/main.go
      - name: Archive build output artifact
        uses: actions/upload-artifact@v3
        with:
          name: rajds-*
          path: rajds-*
          retention-days: 30
